config/routes.rb
CookBook::Application.routes.draw do
  resources :chefs
  resources :recipes
  resources :users, only: [:new, :create]

  root 'static_pages#home'
  get "/about" => "static_pages#about"

  delete '/logout' => 'sessions#logout'

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  
  post '/signup' => 'users#new'

end

app/models/chef.rb
class Chef < ActiveRecord::Base
end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base

  has_secure_password

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private

  def current_user
    if session[:user_id].present?
      @current_user ||= User.find_by(session[:user_id])
    end
  end
  helper_method :current_user
end

app/controllers/chefs_controller.rb
class ChefsController < ApplicationController

  def new
    @chef = Chef.new
  end
  def create
    @chef = Chef.new(chef_params)
    if @chef.save
      flash[:success] = "New Chef added yo!"
      redirect_to chef_path(@chef.id)
    else
      flash[:error] = "Cant save chef yo, for some reason"
      render :new
    end   
  end

  def show
    @chef = Chef.find(params[:id])
  end
  
  def edit
    @chef = Chef.find(params[:id])
  end
  def update
    @chef = Chef.find(params[:id])
    if @chef.update_attributes(chef_params)
      flash[:success] = "Chef updated yo"
      redirect_to chef_path(@chef.id)
    else
      flash[:error] = "Cant update chef yo"
      render :edit
    end    
  end

  def destroy
    @chef = Chef.find(params[:id])
    @chef.destroy
    flash[:notice] = "Chef has been destroyed yo"
    redirect_to chefs_path
  end

  def index
    @chefs = Chef.all
  end  

end

private

  def chef_params
    params.require(:chef).permit(:name, :show, :specialty, :avatar)
  end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController

  def index
    @recipes = Recipe.all
  end

  def show
    @recipe = Recipe.find(params[:id])
  end

  def new
    @recipe = Recipe.new
  end

  def create
    @recipe = Recipe.new(recipe_params)
    if @recipe.save
      flash[:notice] = "You created a recipe yo"
      redirect_to recipe_path(@recipe.id)
    else
      flash[:error] = "There is something wrong yo"
      render :new
    end    
  end

  def edit
    @recipe = Recipe.find(params[:id])
  end

  def update
    @recipe = Recipe.find(params[:id])
    if @recipe.update_attributes(recipe_params)
      flash[:notice] = "Updated recipe yo"
      redirect_to recipe_path(recipe.id)
    else
      flash[:error] = "Cant update yo"
      render :edit  
   end
  end 

  def destroy
    @recipe = Recipe.find(params[:id])
    @recipe.destroy
    flash[:notice] = "Your recipe was destroyed yo"
    redirect_to recipes_path
  end

end

private

  def recipe_params
    params.require(:recipe).permit(:title, :description, :cook_time, :ingredients, :instructions, :picture, :chef_id)
  end
  

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  
  end

  def create
    @user = User.find_by(email: params[:email])
    if @user.try(:authenticate, params[:password])
      session[:current_user] = @user
      redirect_to root_path, notice: "Logged in yo"
    else
      flash[:alert] = "Wrong info yo. U tryin to hack?"
      render :new  
    end  
  end

  def logout
    reset_session
    redirect_to root_path, notice: 'See ya later yo'
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def home

  end

  def about

  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    reset_session #keeps the user from creating when they are signed in
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_path, notice: 'You are signed in yo'
    else
      flash[:alert] = 'You were not signed in yo'
      render :new 
    end  
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chefs_helper.rb
module ChefsHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper

  def options_for_select_chefs
    list_options = []
    chefs = Chef.all
    chefs.each do |chef|
      list_options << ["#{chef.name}", chef.id]
    end
    list_options
  end

end

app/helpers/sessions_helper.rb
module SessionsHelper

  def logged_in?
    current_user.present?
  end

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/chefs/_form.html.erb
<%= form_for(@chef) do |f| %>

  <fieldset>
    <section>
      <%= f.label :name %>
      <%= f.text_field :name %>
    </section>
    <section>
      <%= f.label :show %>
      <%= f.text_field :show %>
    </section>
    <section>
      <%= f.label :specialty %>
      <%= f.text_field :specialty %>
    </section>
    <section>
      <%= f.label :avatar %>
      <%= f.text_field :avatar %>
    </section>
    <section>
      <%= f.submit("Save") %>
    </section>
  </fieldset>

<% end %>

app/views/chefs/edit.html.erb
<h1>Edit Chef</h1>

<%= render('form') %>

app/views/chefs/index.html.erb
<h1>All Chefs YO</h1>

<table>
  <tr>
    <th>Chef</th>
    <th>Show</th>
    <th>Specialty</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @chefs.each do |chef| %>
  <tr>
    <td><%= chef.name %></td>
    <td><%= chef.show %></td>
    <td><%= chef.specialty %></td>
    <td><%= link_to('Show', chef_path(chef.id)) %></td>
    <td><%= link_to('Edit', edit_chef_path(chef.id)) %></td>
   <td><%= link_to('Destroy', chef_path(chef.id), method: :delete, confirm: "Are you sure yo?") %></td>
  </tr>
<% end %>
</table>

app/views/chefs/new.html.erb
<h1>New Chef</h1>

<%= form_for(@chef) do |f| %>

  <fieldset>
    <section>
      <%= f.label :name %>
      <%= f.text_field :name %>
    </section>
    <section>
      <%= f.label :show %>
      <%= f.text_field :show %>
    </section>
    <section>
      <%= f.label :specialty %>
      <%= f.text_field :specialty %>
    </section>
    <section>
      <%= f.label :avatar %>
      <%= f.text_field :avatar %>
    </section>
    <section>
      <%= f.submit("Save") %>
    </section>
  </fieldset>

<% end %>

app/views/chefs/show.html.erb
<h1>Show Chef <small> <%= link_to('edit', edit_chef_path(@chef.id)) %> </small> </h1>

<h2>Chef: <%= @chef.name %></h2>
<br/>
<h3>Specialty: <%= @chef.specialty %></h3>
<h3>Tv Show: <%= @chef.show %></h3>
<div><%= image_tag(@chef.avatar, style: 'width: 150px') %></div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CookBook</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <% flash.each do |name, msg| %>
    <%= content_tag :div, msg, class: name %>
  <% end %>
  
<% if logged_in? %>
  Welcome Yo <%= current_user.name %>
  <%= link_to('Logout', logout_path, method: :delete) %>
<% else %>
  <%= link_to('Login', login_path) %>
  <%= link_to('Sign Up', signup_path) %>
<% end %> 

<nav>
<ul>
  <li><%= link_to "Home", root_path%></li>
  <li><%= link_to "About", about_path%></li>
  <li><%= link_to "Chefs", chefs_path  %></li>
  <li><%= link_to "Recipes", recipes_path %></li>
  <li><%= link_to "New Chef", new_chef_path %></li>
  <li><%= link_to "New Recipe", new_recipe_path %></li>
</ul>
</nav> 

   

<%= yield %>

</body>
</html>

app/views/recipes/_form.html.erb
<%= form_for(@recipe) do |f| %>

<fieldset>
    <section>
      <%= f.label :title %>
      <%= f.text_field :title %>
    </section>
    <section>
      <%= f.label :description %>
      <%= f.text_field :description %>
    </section>
    <section>
      <%= f.label :ingredients %>
      <%= f.text_field :ingredients %>
    </section>
    <section>
      <%= f.label :instructions %>
      <%= f.text_field :instructions %>
    </section>
    <section>
      <%= f.label :cook_time %>
      <%= f.time_field :cook_time %>
    </section>
    <section>
      <%= f.label :picture %>
      <%= f.text_field :picture %>
    </section>
    

    <section>
      <%= f.submit("Save") %>
    </section>
  </fieldset>

<% end %>

app/views/recipes/edit.html.erb
<h1>Edit Recipe</h1>

<%= render('form') %>

app/views/recipes/index.html.erb
<h1>All Recipe's</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Description</th>
    <th>Ingredients</th>
    <th>Instructions</th>
    <th>Picture</th>
    <th>Cook Time</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @recipes.each do |recipe| %>
  <tr>
    <td><%= recipe.title %></td>
    <td><%= recipe.description %></td>
    <td><%= recipe.ingredients %></td>
    <td><%= recipe.instructions %></td>
    <td><%= recipe.picture %></td>
    <td><%= recipe.cook_time %></td>
    <td><%= link_to('Show', recipe_path(recipe.id)) %></td>
    <td><%= link_to('Edit', edit_recipe_path(recipe.id)) %></td>
    <td><%= link_to('Destroy', recipe_path(recipe.id), method: :delete, confirm: "Are you sure yo?") %></td>
  </tr>
<% end %>
</table>

app/views/recipes/new.html.erb
<h1>New Recipe Yo</h1>

<%= render('form') %>

app/views/recipes/show.html.erb
<h1>Recipe <small> <%= link_to('edit', edit_recipe_path(@recipe.id)) %> </small> </h1>

<h2>Recipe : <%= @recipe.title %></h2>
<br/>
<h3>Description : <%= @recipe.description %></h3>
<h3>Ingredients : <%= @recipe.ingredients %></h3>
<h3>Instructions : <%= @recipe.instructions %></h3>
<h3>Picture : <%= @recipe.picture %></h3>
<h3>Cook Time : <%= @recipe.cook_time %></h3>
<div><%= image_tag(@recipe.picture, style: 'width: 150px') %></div>

app/views/static_pages/about.html.erb
<h1>Yo here I am</h1>

app/views/static_pages/home.html.erb
<h1>Time To Cook Like A Thug</H1>

app/views/users/new.html.erb
<h1>New User</h1>

<%= form_for(@user) do |f| %>
  <fieldset>
    <section>
     <%= f.label :name %>
     <%= f.text_field(:name) %> 
    </section>
    <section>
     <%= f.label :email %>
     <%= f.text_field(:email) %> 
    </section>
    <section>
     <%= f.label :password %>
     <%= f.password_field(:password) %> 
    </section>
    <section>
      <%= f.label :password_confirmation %>
      <%= f.password_field(:password_confirmation) %>
    </section>
    <section>
      <%= f.submit("Sign Up Yo!") %>
    </section> 
  </fieldset>

<% end %>